export const userColumns = [
  {
    field: "id",
    headerName: "STT",
    width: 50,
    headerAlign: "center",
    align: "center",
  },
  // {
  //     field: "account",
  //     headerName: "Tài khoản",
  //     width: 150,
  //     minWidth: 130,
  //     maxwidth: 200,
  // },
  {
    field: "name",
    headerName: "Họ tên",
    width: 230,
    minWidth: 180,
    maxwidth: 300,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "email",
    headerName: "Email",
    width: 230,
    minWidth: 200,
    maxwidth: 300,
    headerAlign: "center",
    align: "center",
  },
  // {
  //     field: "phoneNumber",
  //     headerName: "SĐT",
  //     width: 150,
  //     minWidth: 100,
  //     maxwidth: 200,
  // },
  {
    field: "role",
    headerName: "Vai trò",
    width: 100,
    headerAlign: "center",
    align: "center",
  },
];

//temporary data
export const userRows = [
  {
    id: 1,
    account: "nnmc",
    name: "Nguyễn Ngọc Minh Châu",
    email: "19520023@gm.uit.edu.vn",
    phoneNumber: "0783521256",
    role: "Admin",
  },
  {
    id: 2,
    account: "nqm",
    name: "Lê Quang Minh",
    email: "19520023@gm.uit.edu.vn",
    phoneNumber: "0783521256",
    role: "Admin",
  },
  {
    id: 3,
    account: "ndpn",
    name: "Nguyễn Đức Phương Nguyên",
    email: "19520023@gm.uit.edu.vn",
    phoneNumber: "0783521256",
    role: "Admin",
  },
  {
    id: 4,
    account: "nntn",
    name: "Nguyễn Ngọc Thái Nguyên",
    email: "19520023@gm.uit.edu.vn",
    phoneNumber: "0783521256",
    role: "Admin",
  },
  {
    id: 5,
    account: "btdc",
    name: "Bùi Thị Diễn Châu",
    email: "19520023@gm.uit.edu.vn",
    phoneNumber: "0783521256",
    role: "Admin",
  },
  {
    id: 6,
    account: "ltyn",
    name: "Lê Thị Yến Nhi",
    email: "19520023@gm.uit.edu.vn",
    phoneNumber: "0783521256",
    role: "Thường",
  },
  {
    id: 7,
    account: "nnmc",
    name: "Nguyễn Ngọc Minh Châu",
    email: "19520023@gm.uit.edu.vn",
    phoneNumber: "0783521256",
    role: "Admin",
  },
  {
    id: 8,
    account: "nva",
    name: "Nguyễn Văn An",
    email: "19520023@gm.uit.edu.vn",
    phoneNumber: "0783521256",
    role: "Thường",
  },
  {
    id: 9,
    account: "abc",
    name: "A Bê Cê",
    email: "19520023@gm.uit.edu.vn",
    phoneNumber: "0783521256",
    role: "Admin",
  },
  {
    id: 10,
    account: "cba",
    name: "Cê Bê A",
    email: "19520023@gm.uit.edu.vn",
    phoneNumber: "0783521256",
    role: "Thường",
  },
];
